#!/usr/bin/env python3
# DESC: Attribute a webpack bundle's bytes to the npm packages that produced them

"""Answer "what is actually in main.js" from the source map.

`pnpm build` prints one number per chunk and nothing about what is inside it,
which is no use when a bundle is larger than it should be. This walks the source
map's mappings, charges every span of generated bytes to the original file it
came from, and groups the result by npm package.

Needs the .map file beside the .js file, so run it against a build made with
source maps on (CRA's default). Byte counts are pre-gzip; a package's share of
the gzipped file is usually close but not identical.

    scripts/bundle-attrib.py build/static/js/main.*.js
    scripts/bundle-attrib.py build/static/js/main.*.js --top 30 --files
"""

import argparse
import collections
import json
import pathlib
import sys

B64 = {c: i for i, c in enumerate(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")}


def vlq(segment):
    """Decode one base64 VLQ segment into its list of signed fields."""
    out, shift, value = [], 0, 0
    for char in segment:
        digit = B64[char]
        value += (digit & 31) << shift
        if digit & 32:
            shift += 5
        else:
            out.append(-(value >> 1) if value & 1 else value >> 1)
            shift = value = 0
    return out


def attribute(js_path):
    """Return (bytes per source file, unmapped bytes, total bytes)."""
    map_path = js_path.with_name(js_path.name + ".map")
    if not map_path.exists():
        sys.exit(f"bundle-attrib: no source map at {map_path}\n"
                 "  build with source maps on (CRA's default; GENERATE_SOURCEMAP=false disables them)")

    sourcemap = json.loads(map_path.read_text())
    generated = js_path.read_text(errors="replace")

    # Byte offset where each generated line starts, so a (line, column) pair
    # from the mappings can be turned into one absolute position.
    line_starts, offset = [], 0
    for line in generated.split("\n"):
        line_starts.append(offset)
        offset += len(line) + 1

    # Each mapping marks the start of a span; the span runs to the next mark.
    source_index = 0
    marks = []
    for line_no, line in enumerate(sourcemap["mappings"].split(";")):
        column = 0
        for segment in line.split(","):
            if not segment:
                continue
            fields = vlq(segment)
            column += fields[0]
            if len(fields) >= 4:
                source_index += fields[1]
                marks.append((line_starts[line_no] + column, source_index))
    marks.sort()

    total = len(generated)
    per_source = collections.Counter()
    for i, (start, source) in enumerate(marks):
        end = marks[i + 1][0] if i + 1 < len(marks) else total
        if end > start:
            per_source[sourcemap["sources"][source]] += end - start
    return per_source, total - sum(per_source.values()), total


def package_of(path):
    """The npm package a source file belongs to, or a bucket for the rest.

    Prefer pnpm's store directory, `.pnpm/<name>@<version>/`, because it names
    the package unambiguously. Packages that ship their own nested
    node_modules (html2canvas does) otherwise resolve to whatever directory
    happens to follow, which is how html2canvas turns into a package called
    "src".
    """
    if ".pnpm/" in path:
        # <name>@<version>[_<peer>@<version>...], scopes written as @scope+name
        entry = path.split(".pnpm/")[1].split("/")[0]
        name = entry[:entry.index("@", 1)] if "@" in entry[1:] else entry
        return name.replace("+", "/", 1) if name.startswith("@") else name
    if "node_modules/" in path:
        parts = path.split("node_modules/")[-1].split("/")
        return "/".join(parts[:2]) if parts[0].startswith("@") else parts[0]
    if "/webpack/" in path or path.startswith("webpack/"):
        return "(webpack runtime)"
    return "src/ (this app)"


def main():
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Byte counts are pre-gzip. Requires the .map file beside the .js file.")
    parser.add_argument("bundle", type=pathlib.Path, help="path to a built .js file")
    parser.add_argument("--top", type=int, default=20, help="how many rows to print (default 20)")
    parser.add_argument("--files", action="store_true",
                        help="list the heaviest individual source files as well")
    args = parser.parse_args()

    if not args.bundle.exists():
        sys.exit(f"bundle-attrib: no such file: {args.bundle}")

    per_source, unmapped, total = attribute(args.bundle)

    per_package = collections.Counter()
    for path, count in per_source.items():
        per_package[package_of(path)] += count

    print(f"{args.bundle.name}: {total:,} bytes generated")
    for name, count in per_package.most_common(args.top):
        print(f"  {count:>10,}  {100 * count / total:5.1f}%  {name}")
    print(f"  {unmapped:>10,}  {100 * unmapped / total:5.1f}%  (unmapped)")

    if args.files:
        print("\nheaviest source files")
        for path, count in per_source.most_common(args.top):
            print(f"  {count:>10,}  {100 * count / total:5.1f}%  {path}")


if __name__ == "__main__":
    main()
